# FEIZAO
# githubåœ°å€  https://github.com/6Svip120apk69
# TGé¢‘é“åœ°å€  https://t.me/FEIZAOscript
# TGäº¤æµç¾¤    https://t.me/joinchat/feiji-airplaneAAE7XHm-q1-7Np-tF3g
# boxjsé“¾æ¥   https://raw.githubusercontent.com/6Svip120apk69/gitee_q8qsTAUA_cThxc1RBVUE/main/Task/FEIZAO.boxjs.json



# âš ï¸âš ï¸âš ï¸ç‰¹åˆ«é‡è¦,åŠ¡å¿…è¿›è¡Œæ›¿æ¢æ“ä½œï¼Œä¸å¾—ä½¿ç”¨åŸä½œè€…åœ°å€

# å…·ä½“æ–¹æ³•è¯·çœ‹: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions



#  ä»¥è´¦å·    feiji-airplane
#  ä»“åº“åœ°å€  https://github.com/feiji-airplane/JavaScript 
#  æ–‡ä»¶åœ°å€   https://raw.githubusercontent.com/feiji-airplane/JavaScript/FEIZAO/hlyy.js    ä¸ºä¾‹ 


# ä¸»è¦æ›¿æ¢çš„å­—ç¬¦ğŸ‘‡

# è‘«èŠ¦éŸ³ä¹     //jsåå­—
# 0 0-15   //å®šæ—¶ï¼Œå¦‚åŒ—äº¬æ—¶é—´8åˆ°23ç‚¹ï¼Œè®¾ç½®0-15
# hlyyurl   //ç¯å¢ƒå˜é‡ä¹‹ä¸€ï¼Œ47è¡Œå¤„è‡ªè¡Œæ·»åŠ å…¶ä»–
# feiji-airplane      //è´¦å·å
# JavaScript      //ä»“åº“å
# FEIZAO     //åˆ†æ”¯å
# hlyy.js  //å­æ–‡ä»¶åœ°å€




name: è‘«èŠ¦éŸ³ä¹

on:
  workflow_dispatch:
  schedule:
     - cron: '8,38 0-15 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        HLYYURL: ${{ secrets.HLYYURL }}
        HLYYHD: ${{ secrets.HLYYHD }}
        
       
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/feiji-airplane/JavaScript.git ~/JavaScript
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.HLYYURL
        run: |
          cd ~/JavaScript
          git checkout FEIZAO
          npm install
      - name: 'è¿è¡Œ ã€è‘«èŠ¦éŸ³ä¹ã€‘'
        if: env.HLYYURL
        run: |
          cd ~/JavaScript
          node hlyy.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
